package com.acc.datos.hibernate_project.pojos;
// Generated 20 nov 2025, 10:45:11 by Hibernate Tools 6.6.33.Final


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,catalog="proyecto_orm"
)
public class Departamento  implements java.io.Serializable {
     private int idDepto;
     private Sede sede;
     private String nomDepto;
     private Set<Empleado> empleados = new HashSet<Empleado>(0);
    public Departamento() {
    }
    public Departamento(int idDepto, Sede sede, String nomDepto) {
        this.idDepto = idDepto;
        this.sede = sede;
        this.nomDepto = nomDepto;
    }
    public Departamento(int idDepto, Sede sede, String nomDepto, Set<Empleado> empleados) {
       this.idDepto = idDepto;
       this.sede = sede;
       this.nomDepto = nomDepto;
       this.empleados = empleados;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_depto", unique = true, nullable = false)
    public int getIdDepto() {
        return this.idDepto;
    }
    
    public void setIdDepto(int idDepto) {
        this.idDepto = idDepto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_sede", nullable=false)
    public Sede getSede() {
        return this.sede;
    }
    
    public void setSede(Sede sede) {
        this.sede = sede;
    }

    
    @Column(name="nom_depto", nullable=false, length=32)
    public String getNomDepto() {
        return this.nomDepto;
    }
    
    public void setNomDepto(String nomDepto) {
        this.nomDepto = nomDepto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="departamento")
    public Set<Empleado> getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set<Empleado> empleados) {
        this.empleados = empleados;
    }




}


