package com.acc.datos.hibernate_project.pojos;
// Generated 20 nov 2025, 10:45:11 by Hibernate Tools 6.6.33.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,catalog="proyecto_orm"
)
public class Empleado  implements java.io.Serializable {
     private String dni;
     private Departamento departamento;
     private String nomEmp;
     private EmpleadoDatosProf empleadoDatosProf;

    public Empleado() {
    }
    public Empleado(String dni, Departamento departamento, String nomEmp) {
        this.dni = dni;
        this.departamento = departamento;
        this.nomEmp = nomEmp;
    }
    public Empleado(String dni, Departamento departamento, String nomEmp, EmpleadoDatosProf empleadoDatosProf) {
       this.dni = dni;
       this.departamento = departamento;
       this.nomEmp = nomEmp;
       this.empleadoDatosProf = empleadoDatosProf;
    }
     @Id
    @Column(name="dni", unique=true, nullable=false, length=9)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_depto", nullable=false)
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    
    @Column(name="nom_emp", nullable=false, length=40)
    public String getNomEmp() {
        return this.nomEmp;
    }
    
    public void setNomEmp(String nomEmp) {
        this.nomEmp = nomEmp;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="empleado")
    public EmpleadoDatosProf getEmpleadoDatosProf() {
        return this.empleadoDatosProf;
    }
    
    public void setEmpleadoDatosProf(EmpleadoDatosProf empleadoDatosProf) {
        this.empleadoDatosProf = empleadoDatosProf;
    }




}


