package com.acc.datos.hibernate_project.pojos;
// Generated 20 nov 2025, 10:45:11 by Hibernate Tools 6.6.33.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrimaryKeyJoinColumn;
import jakarta.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * EmpleadoDatosProf generated by hbm2java
 */
@Entity
@Table(name="empleado_datos_prof"
    ,catalog="proyecto_orm"
)
public class EmpleadoDatosProf  implements java.io.Serializable {


     private String dni;
     private Empleado empleado;
     private String categoria;
     private Double sueldoBrutoAnual;

    public EmpleadoDatosProf() {
    }

	
    public EmpleadoDatosProf(Empleado empleado, String categoria) {
        this.empleado = empleado;
        this.categoria = categoria;
    }
    public EmpleadoDatosProf(Empleado empleado, String categoria, Double sueldoBrutoAnual) {
       this.empleado = empleado;
       this.categoria = categoria;
       this.sueldoBrutoAnual = sueldoBrutoAnual;
    }

    // --- ¡AQUÍ ESTÁ LA ÚLTIMA CORRECCIÓN! ---
    // Le decimos a Hibernate cómo generar el ID.
    @GenericGenerator(name = "generator", strategy = "foreign",
            parameters = @Parameter(name = "property", value = "empleado")) // -> Le decimos que use el atributo "empleado"
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "dni", unique = true, nullable = false, length = 9)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="categoria", nullable=false, length=2)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="sueldo_bruto_anual", precision=22)
    public Double getSueldoBrutoAnual() {
        return this.sueldoBrutoAnual;
    }
    
    public void setSueldoBrutoAnual(Double sueldoBrutoAnual) {
        this.sueldoBrutoAnual = sueldoBrutoAnual;
    }





}


