package com.acc.datos.hibernate_project.pojos;
// Generated 20 nov 2025, 10:45:11 by Hibernate Tools 6.6.33.Final


import jakarta.persistence.*;

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name="proyecto"
    ,catalog="proyecto_orm"
)
public class Proyecto  implements java.io.Serializable {


     private int idProy;
     private Date FInicio;
     private Date FFin;
     private String nomProy;
     private Set<ProyectoSede> proyectoSedes = new HashSet<ProyectoSede>(0);

    public Proyecto() {
    }

	
    public Proyecto(int idProy, Date FInicio, String nomProy) {
        this.idProy = idProy;
        this.FInicio = FInicio;
        this.nomProy = nomProy;
    }
    public Proyecto(int idProy, Date FInicio, Date FFin, String nomProy, Set<ProyectoSede> proyectoSedes) {
       this.idProy = idProy;
       this.FInicio = FInicio;
       this.FFin = FFin;
       this.nomProy = nomProy;
       this.proyectoSedes = proyectoSedes;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_proy", unique = true, nullable = false)
    public int getIdProy() {
        return this.idProy;
    }
    
    public void setIdProy(int idProy) {
        this.idProy = idProy;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="f_inicio", nullable=false, length=10)
    public Date getFInicio() {
        return this.FInicio;
    }
    
    public void setFInicio(Date FInicio) {
        this.FInicio = FInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="f_fin", length=10)
    public Date getFFin() {
        return this.FFin;
    }
    
    public void setFFin(Date FFin) {
        this.FFin = FFin;
    }

    
    @Column(name="nom_proy", nullable=false, length=20)
    public String getNomProy() {
        return this.nomProy;
    }
    
    public void setNomProy(String nomProy) {
        this.nomProy = nomProy;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyecto")
    public Set<ProyectoSede> getProyectoSedes() {
        return this.proyectoSedes;
    }
    
    public void setProyectoSedes(Set<ProyectoSede> proyectoSedes) {
        this.proyectoSedes = proyectoSedes;
    }





}


