package com.acc.datos.hibernate_project.pojos;
// Generated 20 nov 2025, 10:45:11 by Hibernate Tools 6.6.33.Final


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name="sede"
    ,catalog="proyecto_orm"
)
public class Sede  implements java.io.Serializable {


     private int idSede;
     private String nomSede;
     private Set<Departamento> departamentos = new HashSet<Departamento>(0);
     private Set<ProyectoSede> proyectoSedes = new HashSet<ProyectoSede>(0);

    public Sede() {
    }

	
    public Sede(int idSede, String nomSede) {
        this.idSede = idSede;
        this.nomSede = nomSede;
    }
    public Sede(int idSede, String nomSede, Set<Departamento> departamentos, Set<ProyectoSede> proyectoSedes) {
       this.idSede = idSede;
       this.nomSede = nomSede;
       this.departamentos = departamentos;
       this.proyectoSedes = proyectoSedes;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_sede", unique = true, nullable = false)
    public int getIdSede() {
        return this.idSede;
    }
    
    public void setIdSede(int idSede) {
        this.idSede = idSede;
    }

    
    @Column(name="nom_sede", nullable=false, length=20)
    public String getNomSede() {
        return this.nomSede;
    }
    
    public void setNomSede(String nomSede) {
        this.nomSede = nomSede;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sede")
    public Set<Departamento> getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set<Departamento> departamentos) {
        this.departamentos = departamentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sede")
    public Set<ProyectoSede> getProyectoSedes() {
        return this.proyectoSedes;
    }
    
    public void setProyectoSedes(Set<ProyectoSede> proyectoSedes) {
        this.proyectoSedes = proyectoSedes;
    }






}


